apiVersion: v1
kind: Service
metadata:
  name: {{ template "helm-guestbook.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    project: my-pod
  ports:
    - name: {{ .Values.service.port }}
      protocol: TCP
      port: 80
      targetPort: 80
