replicaCount: 2

image:
  repository: yesinaleksey/k8s-react
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
